title: "Open source e-commerce and marketplaces made simple"

download:
  currentVersion: 0.10
  link: https://github.com/mayocat/mayocat-shop/releases/download/mayocat-shop-0.10/mayocat-shop-distribution-0.10.zip
