title: "Open source e-commerce and marketplaces made simple"

download:
  currentVersion: 0.9.1
  link: https://github.com/mayocat/mayocat-shop/releases/download/mayocat-shop-0.9.1/mayocat-shop-distribution-0.9.1.zip
