title: "Open source e-commerce and marketplaces made simple"

download:
  currentVersion: "0.30.1"
  link: https://github.com/mayocat/mayocat-shop/releases/download/mayocat-shop-0.30.1/mayocat-shop-distribution-0.30.1.zip
